name = "ConicSolveFR"
uuid = "b7e36175-acd1-4b95-9993-0abe5f8513c4"
authors = ["alexander "]
version = "0.0.1"

[deps]
ConicSolve = "1a4286b3-6f5e-4030-bb00-6db9fd4bd7fc"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DataStructures = "0.19.3"
LinearAlgebra = "1.11.0"
